version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prestamos_app
    volumes:
      - ./:/var/www/prestamos
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_COLOR=${APP_COLOR}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    command: unitd --no-daemon

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prestamos_queue
    volumes:
      - ./:/var/www/prestamos
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_DEMO=${APP_DEMO}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    command: php artisan queue:work --sleep=3 --tries=3